# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1a6daada98c6304de24461e2d3b11cc64f6a39859f5b85d4942b571e94a02824cc02139166ee8997787bedb3a71a3ddfdb44c74d372ba32193a433d06f9d9a4

test:
  secret_key_base: a05c646d8faf81b569f79d1d0512b85172b53de7e64dd0efa701dce0f587af2f2289d76aca4a8693b50f120a8dba0cd44251708022b98b29f5f70a9bfaaf7e70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
